### ISSUE TITLE
The sceneview always black

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#535] opened 2019-12-03 07:30 UTC
When I create a new project, sceneview is normal.
But I downloaded the project from the documentation and imported it, and the project's sceneview was always black.
This is the only project where this happens.I tried it on three computers and the results were the same.However, the version before 2019.9 is ok.
Has anyone met this situation and solved it？

**Comment by martins-mozeiko** [comment] 2019-12-03 22:27
Is this duplicate of #532?

**Comment by EricBoiseLGSVL** [comment] 2019-12-05 01:57
@yumianhuli2 

When in scene view, toggle this button off when not in play mode
![help](https://user-images.githubusercontent.com/45106230/70197064-8ab67780-16bf-11ea-8427-6652561aff30.PNG)

**Closed** 2020-04-08 22:13 UTC
