### ISSUE TITLE
LiDAR data delayed against vehicle

### ISSUE THREAD

**Issue by atinfinity** [lgsvl/simulator#677] opened 2020-03-08 14:55 UTC
### System information (version)
- LGSVL Simulator => lgsvlsimulator-linux64-2020.01
- Operating System / Platform => Ubuntu 18.04 64bit
- NVIDIA Driver => nvidia-driver-440
- Vulkan loader library => libvulkan1(1.1.70+dfsg1-1ubuntu0.18.04.1)
- GPU => NVIDIA GeForce RTX 2080 Ti

### Detailed description
I visualized LiDAR data on LGSVL Simulator.
But, LiDAR data delayed against vehicle.

![Screenshot from 2020-03-08 23-53-17](https://user-images.githubusercontent.com/2630323/76165152-0977f080-6198-11ea-8bbd-593a2145e086.png)

### Steps to reproduce
I launched LGSVL Simulator.

```
$ ./lgsvlsimulator-linux64-2020.01/simulator
```

I selected the following setting.

- Screen resolution: 1024 x 768
- Graphics Quality: Ultra

1. I selected Simulator(`BorregasAve, no bridge, data collection`) via Web UI. And, I changed to `WideFlatMap`.
1. I enabled the visualization of LiDAR.
1. I operated vehicle by keyboard.

**Comment by rongguodong** [comment] 2020-03-09 04:08
Can you explain more on your step 1? Do you mean this only happens if you run BorregasAve first, and then run WideFlatMap? How do you "changed to WideFlatMap"?

**Comment by atinfinity** [comment] 2020-03-09 04:36
@rongguodong Sorry for not explaining enough. I attached screenshot.

> I selected Simulator(BorregasAve, no bridge, data collection) via Web UI.

![image](https://user-images.githubusercontent.com/2630323/76183095-922f7480-620a-11ea-87b4-7097b990eb42.png)

> And, I changed to WideFlatMap.

![image](https://user-images.githubusercontent.com/2630323/76183143-c014b900-620a-11ea-8d32-6798b64d6a2f.png)

**Comment by rongguodong** [comment] 2020-03-09 15:56
I tried the latest build on my Linux machine and cannot reproduce this issue. See my screenshot as below:
![Screenshot from 2020-03-09 08-52-48](https://user-images.githubusercontent.com/11858549/76232375-d6f3e500-61e3-11ea-806f-fc04e787996b.png)

**Comment by rongguodong** [comment] 2020-03-09 15:59
What I did is:
* Download the latest build: https://github.com/lgsvl/simulator/releases/download/2020.01/lgsvlsimulator-linux64-2020.01.zip
* Unzip and run it
* Click "Open Browser" button to open the WebUI. (All assets will be automatically downloaded)
* Go to "Simulation" page and select the first simulation. Change its map to "WildFlatMap", and run it.

If you did anything different, please let me know.

**Comment by atinfinity** [comment] 2020-03-09 23:20
I turned up the vehicle speed by the operation of keyboard.

**Comment by rongguodong** [comment] 2020-03-10 00:20
If the speed is too fast, maybe the Lidar points are not generated fast enough to catch the ego car. As long as the ego car slow down or stops, the Lidar points should be correct.

**Comment by atinfinity** [comment] 2020-03-16 10:13
@rongguodong Thank you for your reply. Is there a workaround besides slowing down the car?

**Comment by EricBoiseLGSVL** [comment] 2020-04-16 19:28
@atinfinity Most AD stacks we support do not support EGO vehicles at high speed.  We are working on RTX support and UDP LiDAR sensors to improve performance but this will be in a future release

**Comment by atinfinity** [comment] 2020-04-17 11:03
@EricBoiseLGSVL Thank you for your reply. I understood about future plan.

**Closed** 2020-04-17 17:20 UTC

**Comment by ZeKubiki** [comment] 2020-12-10 22:35
@EricBoiseLGSVL just curious how it's going with the RTX and UDP Lidar updates. Very much looking forward to it. Do you have an expected release date?

**Comment by EricBoiseLGSVL** [comment] 2020-12-11 01:14
@ZeKubiki we have a UDP Velodyne Lidar solution now but it is not open source at the moment.  We are still working on issues with RTX and Linux.
