### ISSUE TITLE
Screen Loading......

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#504] opened 2019-11-19 09:35 UTC
Hello！The simulation test is running without any error, But unity has been stuck in the loading screen,I can't get into the scene. What is the reason for this？

The only available message is "Failed to read GPU texture".

![Screenshot from 2019-11-19 17-32-08](https://user-images.githubusercontent.com/39210837/69134523-8fd9cb00-0af2-11ea-8d02-f297e7371c78.png)

![Screenshot from 2019-11-19 17-23-31](https://user-images.githubusercontent.com/39210837/69134379-5acd7880-0af2-11ea-97f6-760515202237.png)

**Comment by martins-mozeiko** [comment] 2019-11-19 19:05
Can you please check log file to see if it has any error message? Log file locations: https://www.lgsvlsimulator.com/docs/faq/#where-are-unity-log-files-located

**Comment by yumianhuli2** [comment] 2019-11-20 01:43
Desktop is 1920 x 1080 @ 120 Hz
[Vulkan init] extensions: count=14
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_KHX_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
Vulkan detection: 2
Initialize engine version: 2019.1.10f1 (f007ed779b7a)
GfxDevice: creating device client; threaded=1
[Vulkan init] extensions: count=14
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_KHX_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: count=33
[Vulkan init] extensions: name=VK_KHR_swapchain, enabled=1
[Vulkan init] extensions: name=VK_KHR_descriptor_update_template, enabled=0
[Vulkan init] extensions: name=VK_KHR_dedicated_allocation, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_memory_requirements2, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance1, enabled=1
[Vulkan init] extensions: name=VK_KHR_push_descriptor, enabled=0
[Vulkan init] extensions: name=VK_KHR_sampler_mirror_clamp_to_edge, enabled=1
[Vulkan init] extensions: name=VK_KHR_shader_draw_parameters, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_fd, enabled=0
[Vulkan init] extensions: name=VK_KHX_device_group, enabled=0
[Vulkan init] extensions: name=VK_KHX_external_memory, enabled=0
[Vulkan init] extensions: name=VK_KHX_external_memory_fd, enabled=0
[Vulkan init] extensions: name=VK_KHX_external_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHX_external_semaphore_fd, enabled=0
[Vulkan init] extensions: name=VK_KHX_multiview, enabled=0
[Vulkan init] extensions: name=VK_EXT_discard_rectangles, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_ballot, enabled=0
[Vulkan init] extensions: name=VK_EXT_shader_subgroup_vote, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_control, enabled=0
[Vulkan init] extensions: name=VK_NV_dedicated_allocation, enabled=0
[Vulkan init] extensions: name=VK_NV_glsl_shader, enabled=0
[Vulkan init] extensions: name=VK_NV_clip_space_w_scaling, enabled=0
[Vulkan init] extensions: name=VK_NV_sample_mask_override_coverage, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_array2, enabled=0
[Vulkan init] extensions: name=VK_NV_viewport_swizzle, enabled=0
[Vulkan init] extensions: name=VK_NV_geometry_shader_passthrough, enabled=0
[Vulkan init] extensions: name=VK_NVX_device_generated_commands, enabled=0
[Vulkan init] extensions: name=VK_NVX_multiview_per_view_attributes, enabled=0
Vulkan API version 1.0.49
Vulkan vendor=[NVIDIA] id=[10de]
Vulkan renderer=[GeForce GTX 1080 with Max-Q Design] id=[1be0]
Vulkan device type 2
Vulkan driverversion=[0x60208000] uint=[1612742656]
Vulkan PSO: Cache data successfully loaded [size=1361211,path=/tmp/LG Silicon Valley Lab/LGSVL Simulator/vulkan_pso_cache.bin]
Begin MonoManager ReloadAssembly
- Completed reload, in  0.634 seconds
WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - All passes removed
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - Setting to default shader.
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'IndirectDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'ForwardDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - Pass 'VisibilityDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Lit' - All passes removed
requesting resize 1280 x 960
resizing window to 1280 x 960
Desktop is 1920 x 1080 @ 120 Hz
InitializeOrResetSwapChain 1280x960 samples=1
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
UnloadTime: 6.426865 ms
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'IndirectDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'ForwardDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - Pass 'VisibilityDXR' has no vertex shader
WARNING: Shader Unsupported: 'HDRP/Unlit' - All passes removed
Current Database Version: 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Final Database Version: 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 7fc049ea3700 -> priority: 1 
  Thread -> id: 7fc0496a2700 -> priority: 1 
  Thread -> id: 7fc048ea1700 -> priority: 1 
  Thread -> id: 7fc013fff700 -> priority: 1 
Cannot create required material because shader is null
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot create required material because shader is null
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

requesting resize 1280 x 960
resizing window to 1280 x 960
Desktop is 1920 x 1080 @ 120 Hz
InitializeOrResetSwapChain 1280x960 samples=1
Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing UAV ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Compute dispatch: missing texture ID %d
 
(Filename:  Line: 0)

Getting current user
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/libKernel32
Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/libKernel32.so
Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/Kernel32
Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/libKernel32
Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/libKernel32.so
Fallback handler could not load library /home/kakuhin/Music/lgsvlsimulator-linux64-2019.09/simulator_Data/Mono/libKernel32
Listing maps
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing simulations
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing maps
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing simulations
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing simulations
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Getting simulation with id 1
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing maps
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing maps
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing vehicles
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Listing cluster
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Vulkan PSO: Pipeline cache has not changed skipping save handle[47ba0f0]
GarbageCollector disposing of ComputeBuffer. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Culling group was not disposed. You have to call Dispose explicitly from the main thread. This will likely result in a crash.
 
(Filename: /home/builduser/buildslave/unity/build/Runtime/Export/Camera/CullingGroup.bindings.cpp Line: 70)

Preloaded type GtkListStore
Preloaded type GtkWindow
Preloaded type GtkVBox
Preloaded type GtkImage
Preloaded type GtkNotebook
Preloaded type GtkHBox
Preloaded type GtkFrame
Preloaded type GtkAlignment
Preloaded type GtkTreeView
Preloaded type GtkLabel
Preloaded type GtkCheckButton
Preloaded type GtkScrolledWindow
Preloaded type GtkComboBox


It's all about play.log!And the only "error" message seems ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/Nature/Terrain/Utilities' - Setting to default shader.
Plz help me check this, Thank you very much indeed!

**Comment by david-gwa** [comment] 2019-11-26 08:11
do you have   /tmp/LG\ Silicon\ Valley\ Lab/LGSVL\ Simulator/vulkan_pso_cache.bin ?   I don't understand the reason, but this cache file may helps

**Comment by mmozeiko** [comment] 2019-11-26 08:33
@david-gwa  That file is not a problem here. It is internal to Unity for caching Vulkan pipeline state object.

@yumianhuli2 I think the log file you posted is incomplete. Because first thing that happens when you press red play button in WebUI is [this line](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Web/Modules/SimulationsModule.cs#L474) - thus log file should contain `Starting simulation with id` text. But I don't see it here.

Last few lines in log file suggests you clicked on Clusters section in WebUI. Try first close simulator, delete whole log file, then run simulator again and only click red play button to start simulation

**Comment by martins-mozeiko** [comment] 2019-11-26 08:42
@david-gwa  That file is not a problem here. It is internal to Unity for caching Vulkan pipeline state object.

@yumianhuli2 I think the log file you posted is incomplete. Because first thing that happens when you press red play button in WebUI is [this line](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Web/Modules/SimulationsModule.cs#L474) - thus log file should contain `Starting simulation with id` text. But I don't see it here.

Last few lines in log file suggests you clicked on Clusters section in WebUI. Try first close simulator, delete whole log file, then run simulator again and only click red play button to start simulation

**Comment by EricBoiseLGSVL** [comment] 2020-04-08 22:03
@yumianhuli2 We are currently working on a fix for this issue.  The problem is Linux and LiDAR sensor GPU readback

**Comment by yumianhuli2** [comment] 2020-04-09 00:29
> The problem is Linux and LiDAR sensor GPU readback

ok！Could you tell me when the problem will be fixed?

**Comment by EricBoiseLGSVL** [comment] 2020-04-09 15:43
@yumianhuli2 we are hoping this month

**Comment by yumianhuli2** [comment] 2020-04-10 03:07
> @yumianhuli2 we are hoping this month

Nice!

**Comment by EricBoiseLGSVL** [comment] 2020-04-16 17:58
@yumianhuli2 Are you running Clusters still on this simulation?

**Comment by yumianhuli2** [comment] 2020-04-17 02:03
Could I understand that your team have fixed this bug?

**Comment by EricBoiseLGSVL** [comment] 2020-04-17 17:21
@yumianhuli2 We will have a release later this month that will resolve this

**Comment by yumianhuli2** [comment] 2020-04-18 09:35
> @yumianhuli2 We will have a release later this month that will resolve this

OK! I will wait for this!Thank U!

**Comment by yumianhuli2** [comment] 2020-05-14 09:46
> @yumianhuli2 We will have a release later this month that will resolve this

Hello！ Have you resolved this bug？

**Comment by EricBoiseLGSVL** [comment] 2020-05-14 16:30
@yumianhuli2 we plan on a release this month with this fix

**Comment by yumianhuli2** [comment] 2020-05-15 03:00
> @yumianhuli2 we plan on a release this month with this fix

very Nice！

**Comment by yumianhuli2** [comment] 2020-06-09 00:14
> @yumianhuli2 we plan on a release this month with this fix

Hi！Has this bug been fixed？

**Comment by EricBoiseLGSVL** [comment] 2020-06-09 03:18
@yumianhuli2 We have released 2020.05 and it should fix GPU read back errors on Linux.  Please let us know if you still have issues.  Are you able to run a simulation?

**Comment by yumianhuli2** [comment] 2020-06-10 09:35
> @yumianhuli2 We have released 2020.05 and it should fix GPU read back errors on Linux. Please let us know if you still have issues. Are you able to run a simulation?
Thank you！I will try ！

**Comment by yumianhuli2** [comment] 2020-06-17 09:12
> @yumianhuli2 We have released 2020.05 and it should fix GPU read back errors on Linux. Please let us know if you still have issues. Are you able to run a simulation?

OK，It works！

**Closed** 2020-06-17 15:56 UTC
Labels: answered, question
