### ISSUE TITLE
Rviz automatically disappear after running for a few seconds

### ISSUE THREAD

**Issue by Felixgithub2017** [lgsvl/simulator#96] opened 2019-02-27 14:49 UTC
I am following the instructions of Autoware with LG SVL Simulator, everything seems fine, however when I click the Localization tap, I think there should be a time displayed to the right of  "Ref", but it just doesn't show up.

One more problem, when I click the Rviz button, it just open and running for a few seconds and then disappear automatically.

This always happens, I tried many times.

![image](https://user-images.githubusercontent.com/26135691/53497831-0c012e00-3ae0-11e9-9a92-cf4c0e244819.png)

**Comment by hadiTab** [comment] 2019-02-27 20:01
The time displayed to the right of Ref doesn't show up until localization has a good estimate. You may need to drive for a while or you may be having other issues with localization. It would be a bit easier to debug this in rviz.

Do you get any error messages when rviz crashes?
What if you try launching rviz manually from a terminal using `rosrun rviz rviz`?

**Comment by Felixgithub2017** [comment] 2019-03-01 07:10
> The time displayed to the right of Ref doesn't show up until localization has a good estimate. You may need to drive for a while or you may be having other issues with localization. It would be a bit easier to debug this in rviz.
> 
> Do you get any error messages when rviz crashes?
> What if you try launching rviz manually from a terminal using `rosrun rviz rviz`?

This is what the terminal looks like after "RViz" is clicked, then it crashed
![image](https://user-images.githubusercontent.com/26135691/53620943-cce1f280-3c2f-11e9-84e3-6b22cab1a4bc.png)

![image](https://user-images.githubusercontent.com/26135691/53620972-e71bd080-3c2f-11e9-94d8-d8fee030af84.png)

Then I opened another terminal, tried "rosrun rviz rviz", I got the following:
![image](https://user-images.githubusercontent.com/26135691/53621819-c9039f80-3c32-11e9-8084-54d56e4cc86d.png)


The followings are the output of terminal after Autoware is started.
This is what the terminal looks like after Autoware is started:
![image](https://user-images.githubusercontent.com/26135691/53620128-bd14df00-3c2c-11e9-8bcb-7cbff1254e07.png)

This is what the terminal looks like after "Map" tab is clicked:
![image](https://user-images.githubusercontent.com/26135691/53620169-f0576e00-3c2c-11e9-8518-9a089b0bc9d2.png)

![image](https://user-images.githubusercontent.com/26135691/53620183-fc433000-3c2c-11e9-9d22-2c675aaa148f.png)

![image](https://user-images.githubusercontent.com/26135691/53620197-0a914c00-3c2d-11e9-8d79-c4018ac4d9ca.png)

This is what the terminal looks like after "Sensing" is clicked.
![image](https://user-images.githubusercontent.com/26135691/53620210-1aa92b80-3c2d-11e9-8a95-9971c1e5a35e.png)

![image](https://user-images.githubusercontent.com/26135691/53620357-a28f3580-3c2d-11e9-8502-28cfa737ce2b.png)

This is what the terminal looks like after "Localization" is clicked.
![image](https://user-images.githubusercontent.com/26135691/53620376-ad49ca80-3c2d-11e9-8ce8-323b7e8bc957.png)

![image](https://user-images.githubusercontent.com/26135691/53620394-bcc91380-3c2d-11e9-80cc-2e1794d2f445.png)

![image](https://user-images.githubusercontent.com/26135691/53620400-c81c3f00-3c2d-11e9-8b81-bb639987378b.png)

This is what the terminal looks like after "Detection" is clicked.
![image](https://user-images.githubusercontent.com/26135691/53620464-06b1f980-3c2e-11e9-8d9a-1315b4c661ed.png)

![image](https://user-images.githubusercontent.com/26135691/53620478-13cee880-3c2e-11e9-855c-3393e57d436e.png)

![image](https://user-images.githubusercontent.com/26135691/53620504-2f39f380-3c2e-11e9-844d-2b2c0c20a48f.png)

![image](https://user-images.githubusercontent.com/26135691/53620527-424cc380-3c2e-11e9-824b-e6eeaa7e52e9.png)

![image](https://user-images.githubusercontent.com/26135691/53620538-4ed11c00-3c2e-11e9-8e4d-808a4e360f87.png)

![image](https://user-images.githubusercontent.com/26135691/53620556-601a2880-3c2e-11e9-828b-f30fb507f23e.png)

![image](https://user-images.githubusercontent.com/26135691/53620588-77f1ac80-3c2e-11e9-9984-21055aae0a78.png)

![image](https://user-images.githubusercontent.com/26135691/53620606-8344d800-3c2e-11e9-8061-0e8e9faec576.png)

This is what the terminal looks like after "Mission Planning" is clicked.
![image](https://user-images.githubusercontent.com/26135691/53620645-a5d6f100-3c2e-11e9-955d-e21fce6c5f63.png)

![image](https://user-images.githubusercontent.com/26135691/53620654-ad969580-3c2e-11e9-9600-9f38ea1e8be7.png)

![image](https://user-images.githubusercontent.com/26135691/53620660-b5563a00-3c2e-11e9-8024-8a83424e80a7.png)

This is what the terminal looks like after "Motion Planning" is clicked.
![image](https://user-images.githubusercontent.com/26135691/53620676-cacb6400-3c2e-11e9-9f89-f08380dd26bd.png)

![image](https://user-images.githubusercontent.com/26135691/53620705-ddde3400-3c2e-11e9-83e5-04778737d225.png)

![image](https://user-images.githubusercontent.com/26135691/53620751-0f56ff80-3c2f-11e9-884b-cd4d42b4a3ac.png)

![image](https://user-images.githubusercontent.com/26135691/53620772-20077580-3c2f-11e9-99ae-24dd392ebc6c.png)



This is what the terminal looks like after "RViz" is clicked, then it crashed
![image](https://user-images.githubusercontent.com/26135691/53620943-cce1f280-3c2f-11e9-84e3-6b22cab1a4bc.png)

![image](https://user-images.githubusercontent.com/26135691/53620972-e71bd080-3c2f-11e9-94d8-d8fee030af84.png)

**Comment by hadiTab** [comment] 2019-03-01 08:07
@Felixgithub2017 It seems like the issue is with the configuration file with rviz (since your rviz is opening normally).
Can you check and see if the config file exists in the directory as shown in your terminal output? This is the directory I'm talking about: `~/autoware/ros/src/.config/rviz/default.rviz`

A workaround for your problem could be to manually launch rviz using `rosrun rviz rviz` and then click on File > Open Config and navigate to the config file.

**Comment by hadiTab** [comment] 2019-03-01 21:26
@Felixgithub2017 I was able to recreate your issue. It seems like there is a bug in the vector map that is causing this. We will be pushing a fix for it to the autoware-data repository soon. In the mean time, you can checkout an older commit.
For example:
```
cd ~/shared_dir/autoware-data/
git checkout 686ed57
```
Once we push the fix you can checkout master again.

**Comment by tjh49** [comment] 2019-03-28 12:36
Hello, @hadiTab 
Do you fix the issue about a bug in the vector map?

**Comment by hadiTab** [comment] 2019-03-28 20:27
@tjh49 the fix has been pushed to master. Are you still having this issue?

**Comment by tjh49** [comment] 2019-03-29 03:40
I have the similar issue .As follows:
1)when I click the Localization tap, I think there should be a time displayed to the right of "Ref", but it just doesn't show up. Can be time message  displayed?  Does this indicate that the lidar positioning(ndt_matching) was not successful in autoware?
2)When using rviz to show vector map,rviz become quite slow,so I don't know how to deal with it .

**Comment by hadiTab** [comment] 2019-03-29 19:29
@tjh49 
1) I believe the number only shows up when the ndt matching algorithm gets a good match. This may or may not happen immediately and really depends on the algorithm and other factors. You shouldn't have localization issues as long as GPS is enabled though since the GPS in our simulator does not have any errors. The point cloud we load as PCD files was artificially generated from the Unity scene and not collected by the simulated lidar. As a result ndt matching doesn't work as well as if the data was collected by the same lidar. You can try building your own pointcloud map by driving around in the simulator and using that for ndt matching instead. If you don't really care about using ndt matching, and just need good localization I would suggest just using the current setup which uses GPS.

2) Unfortunately the Vector Map really slows down rviz and there is not much that can be done about it. You can try unchecking features from the Vector Map so that they are not displayed in rviz, but it will be difficult to generate routes with out displaying the lane centerlines (which are very slow to display in rviz). You may just have to wait a few minutes for everything to load before using it (and it will still be slow).

3) That error is related to obstacle detection using SSD which seems to be crashing. I'm not sure why it is crashing, but it really isn't used for driving around in Autoware so it shouldn't affect anything. You can ignore it for now.

**Comment by martins-mozeiko** [comment] 2019-08-19 23:10
We have verified that our newest simulator release [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) works with latest Autoware release 1.12 without any changes to Autoware code.

Please check that this issue is still happening with Autoware code.

**Closed** 2020-04-07 16:00 UTC
