### ISSUE TITLE
About ray tracing support

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#424] opened 2019-10-10 07:39 UTC
Unity has released a version of ray tracing,Has ray tracing been supported?Thank U!

**Comment by martins-mozeiko** [comment] 2019-10-10 14:14
If I'm not mistaken, the DXR support in Unity is still in preview, not in stable version. So nothing has changed from situation mentioned in #364.

That said, if you are interested in working on this, we would gladly accept pull request.

Closing issue, as it is duplicate of #364. Please continue discussion in one place.

**Closed by martins-mozeiko** 2019-10-10 14:14 UTC

**Comment by yumianhuli2** [comment] 2019-10-11 06:59
> If I'm not mistaken, the DXR support in Unity is still in preview, not in stable version. So nothing has changed from situation mentioned in #364.
> 
> That said, if you are interested in working on this, we would gladly accept pull request.
> 
> Closing issue, as it is duplicate of #364. Please continue discussion in one place.

ok thanks!
