### ISSUE TITLE
How to Add a New Ego Vehicle

### ISSUE THREAD

**Issue by DestinyFrank** [lgsvl/simulator#1547] opened 2021-07-05 16:22 UTC
I am having problems 

creating a new ego vehicle in the SVL Simulator. I have been following this tutorial ( https://www.svlsimulator.com/docs/simulation-content/add-new-ego-vehicle/). After completing the steps for preparing the asset in Maya. The main issue I am having is launching the svl simulator from the unity editor. When that wasn't working I tried to continue with setting up the vehicle in Unity. However, I keep getting error messages when I try to Build the simulator in unity. I have also tried to upload the vehicle as a  unity asset bundle directly into the website, but it does not match the requested type. Any help would be greatly appreciated.
Thank you. 
![s](https://user-images.githubusercontent.com/86273840/124499058-60d9a100-dd8b-11eb-8b74-84a79dced3cb.PNG)

**Comment by heeen** [comment] 2021-07-06 09:04
What operating system/platform are you developing on? Is it 32bit or 64 bit?

**Comment by DestinyFrank** [comment] 2021-07-06 14:36
My operating system is 64 bit.

**Comment by heeen** [comment] 2021-07-06 14:53
Windows or Linux?

**Comment by DestinyFrank** [comment] 2021-07-06 15:17
My computer is Windows.

**Comment by EricBoiseLGSVL** [comment] 2021-07-06 22:59
@DestinyFrank hello and awesome you are creating a new vehicle for svl simulator.  It is a complex process and I hope I can help.

A few things before building a vehicle:
- You seem to have a corrupted database.  Go to C:\Users\YOU\AppData\LocalLow\LGElectronics and delete the SVLSimulator folder.  Then download the latest binary and run it.  Link the simulator to the cloud and then run a simple simulation to test issues running the sim (cubetown, jag with only keyboard sensor).  Copy the config.yml file in the binary and add it to the simulator source root folder (unity project) if it is not there.
- You need to run the simulator in the Unity Editor by starting the LoaderScene.scene.  If you complete the above steps, the editor will run the simulator just like a binary.

Let me know how it goes to run the simulator first and then post the errors you are having building. Errors are in the player.log for the binary and in the console window for the Editor.

A few things to check before trying to build again:
1) be sure Linux mono build support is installed in your windows Unity installation.
2) be sure you have the right version installed. 2019.4.18f1 is the version for 2021.1.1 release.
3) be sure you are placing all assets in Assets/External/Vehicles/YourVehicle.
4) vehicle prefab needs to be named YourVehicle.

Try again, post errors and take a screen shot of the vehicle in the Unity Editor with a view of the Hierarchy Panel and a screen shot of the bundle opened with a zip program (the bundle is just a zip and you can open it to see what files are missing).

**Comment by DestinyFrank** [comment] 2021-07-07 18:49
@EricBoiseLGSVL  Thank you for your help. I was able to build the vehicle in Unity and upload it to the simulator website. I am getting an error that the versions are mismatched. I checked the other vehicles in the library and it seems that the rest are for simulator 3 while ours in simulator 5. Is there a way to change the version or do I need to change building it in Unity. 
![SVL_Simulator_Robot](https://user-images.githubusercontent.com/86273840/124812819-1ba3a380-df32-11eb-9480-b08b8a524d00.PNG)
![SVL_Simulator_Robot_1](https://user-images.githubusercontent.com/86273840/124812855-25c5a200-df32-11eb-94d0-1cd9bff206b4.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-07 21:38
Glad to help.  We have been updating webui all day today. Try to clear cookies, sign out and sign back in.  See if the assets have been updated.

**Comment by DestinyFrank** [comment] 2021-07-12 17:17
Hi, @EricBoiseLGSVL I am trying to get the vehicle to show when I run the simulation. I changed the configuration and I am trying to select a bridge to see if that helps. I tried using the ROS bridge because it is the same as the other vehicle I used. However, when I try to select an autopilot it says that it is not compatible with the selected vehicle's bridge. I tried another bridge-type but it says the same thing. Is there a different bridge I need to use or an update? 
![SVL_Capture_5](https://user-images.githubusercontent.com/86273840/125327224-e1128000-e310-11eb-9660-10f4a72e4aa2.PNG)
![SVL_Capture_6](https://user-images.githubusercontent.com/86273840/125327242-e7086100-e310-11eb-9a58-f96b77315a24.PNG)
![SVL_Capture_7](https://user-images.githubusercontent.com/86273840/125327255-e96abb00-e310-11eb-8f2f-533afa44dea1.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-12 21:50
Yes we have removed bridges from the source code and posted to github. I recommend creating a new vehicle and use the new bridge in webui.  Sorry for the confusion.

**Comment by DestinyFrank** [comment] 2021-07-12 23:13
Okay, thank you for letting me know. I am still a little confused about where is the WebUI is? Is there a setting when you upload the AssetBundle to the website or is that in Unity? After trying again I think I fixed the issue with the ROS bridge. I was able to select  Autoware.AI v1.12 for the Autopilot and it was able to run the simulation. I am still not able to see our vehicle in the simulation view. 
![SVL_Capture_8](https://user-images.githubusercontent.com/86273840/125366774-c9ed8580-e344-11eb-9a2f-4e55e206c066.PNG)
![SVL_Capture_9](https://user-images.githubusercontent.com/86273840/125366902-1a64e300-e345-11eb-954e-c7f64f59051f.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-12 23:30
hmm it is loaded.  What is the scale? Can you post the bundle here?

**Comment by DestinyFrank** [comment] 2021-07-13 15:42
My original scale was 1 I tried I changed it to 2 to see if that would help. The vehicle is still not showing when I run the simulation it does show in the Vehicles Library. 
![SVL_Capture_10](https://user-images.githubusercontent.com/86273840/125482195-c868eb6d-97f6-4541-89ba-218812836722.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-13 16:44
Can you run the simulation in the Editor so we can look to see what Unity is spawning?  The camera is centered at the spawn point so it seems the issue is the vehicle itself.  Please run loader, then the simulation and then open AgentManager under SimulationManager to select the vehicle.  Then you can press F to snap to the agent.  Let's get a screen shot of the vehicle in the hierarchy panel.

**Comment by DestinyFrank** [comment] 2021-07-13 17:53
I am not able to run the simulation from the Unity editor. When I  have tried to run the simulation in unity I have gotten errors. I am also having a hard time finding the settings you are talking about in Unity I apologize. 

![SVL_Capture_10](https://user-images.githubusercontent.com/86273840/125501307-9b0508a8-14d8-49c8-a525-6cdab01b39b5.PNG)
![SVL_Capture_11](https://user-images.githubusercontent.com/86273840/125501309-8f13f583-c33f-4ab0-b764-756f1eb6e1bd.PNG)
![SVL_Capture_12](https://user-images.githubusercontent.com/86273840/125501310-c4794943-17d3-408e-a1b7-9a5ece0f0dce.PNG)

**Comment by DestinyFrank** [comment] 2021-07-13 18:39
Here is the asset bundle of the vehicle I am using. 
[vehicle_Robot_Medium_ALL_2.zip](https://github.com/lgsvl/simulator/files/6811204/vehicle_Robot_Medium_ALL_2.zip)

**Comment by EricBoiseLGSVL** [comment] 2021-07-13 20:51
First off, don't run editor simulation with developer settings.  Run the LoaderScene.  Then look at the game object that spawns for your vehicle in the Hierarchy Panel while a simulation is running.  We need to see what Unity is spawning as an agent.  That way you can see if the pivot is off or the mesh is missing.

The meshes look ok but we need to see how you placed the pivot point of the mesh and holder object.
Does your pivots look like these?
![image](https://user-images.githubusercontent.com/45106230/125523050-557409b4-0360-483a-bb5f-5ae6935fafb6.png)
![image](https://user-images.githubusercontent.com/45106230/125523121-c1e1edd9-aa13-448c-b0a1-c0f95c32f176.png)

Are the pivots at the bottom of the model, not at the bottom of the chassis?

**Comment by EricBoiseLGSVL** [comment] 2021-07-13 20:53
The issue with your build is that webui is not able to get a version from your locally built binary of simulator.  We are working on a fix and should push very soon.

**Comment by DestinyFrank** [comment] 2021-07-14 14:17
I apologize it been a while since I've used Unity what do you mean by  Run the LoaderScene? Here are images where the pivots on the vehicle is this correct? 
![SVL_Capture_15](https://user-images.githubusercontent.com/86273840/125636649-7ea52da9-6640-47ec-b88a-b4bc7ddc6447.PNG)
![SVL_Capture_16](https://user-images.githubusercontent.com/86273840/125636652-98e5943d-2960-4346-8962-7210b9851d4e.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-14 21:45
The pivot in local space is not right I think.  Look again at the images I posted and the underline in red.  Notice the gizmo is at the bottom of the vehicle, not in the middle.  Vehicles are placed at the spawn point at this position in world space.  So in simulator, the vehicle is placed mid way in the road collision mesh, and falls through.  If you look in the editor when the simulator starts, I bet the vehicle is falling below the map. (Check local space is toggled on in the top left, you cut it out of the image you posted and you can see in mine)

Loaderscene is the scene in the editor you start with play mode to test.  It loads the main menu and you can run simulations just like a binary. Look for it in Assets/Scenes.

Doc [here](https://www.svlsimulator.com/docs/simulation-content/add-new-ego-vehicle/) video at 0:19 for origin point.

**Comment by DestinyFrank** [comment] 2021-07-15 16:15
I changed it to Pivot and local and it seems to be at the right spot below the vehicle. I was able to do the find Loaderscene but when I pressed play it said that it was disconnected and that it does not match the linked version 2021.2. Since I changed to the gizmo setting should I try to build the vehicle again and uploaded it to the website again? 




![SVL_Capture_17](https://user-images.githubusercontent.com/86273840/125820332-6f335362-5dfc-4ca6-bae1-5d1fed6c67df.PNG)
![SVL_Capture_18](https://user-images.githubusercontent.com/86273840/125820333-b92b82d4-d98d-4d91-9d03-8c64705bceef.PNG)
![SVL_Capture_19](https://user-images.githubusercontent.com/86273840/125820335-894f5b8e-fddb-41e9-bf08-24ae32232833.PNG)
![SVL_Capture_20](https://user-images.githubusercontent.com/86273840/125820336-9f793e9a-95de-46e6-b815-8c8f880b8896.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-15 17:08
Since the cluster is linked to the binary that is 2021.2 and the editor is technically Development you need to unlink the cluster and link with the editor.  Then 2021.2 and the editor will both work.  You can also add a data_path to the binary so it uses a different simid and cache folder.

**Comment by DestinyFrank** [comment] 2021-07-15 17:21
I deleted that original cluster and connected it to the one in the Loaderscene but it's now saying that is not compatible with the simulation cluster version.
![SVL_Capture_21](https://user-images.githubusercontent.com/86273840/125830186-29ad11c3-2814-4278-8e0e-4b0f24407432.PNG)
![SVL_Capture_22](https://user-images.githubusercontent.com/86273840/125830187-fd22d8a1-3044-44aa-a0d5-44d82bf29525.PNG)
![SVL_Capture_23](https://user-images.githubusercontent.com/86273840/125830188-7872a8df-6dab-4f50-94e3-6ec0a92f79fd.PNG)
![SVL_Capture_24](https://user-images.githubusercontent.com/86273840/125830189-b3b69091-11de-40bb-83ac-daaef1cff159.PNG)




![SVL_Capture_21](https://user-images.githubusercontent.com/86273840/125830058-3c84cc31-d320-4dea-9ba3-1c34f23ba837.PNG)
![SVL_Capture_22](https://user-images.githubusercontent.com/86273840/125830062-86357455-2dc5-4785-8793-1daa125476d5.PNG)
![SVL_Capture_23](https://user-images.githubusercontent.com/86273840/125830064-9feacfdd-8773-4267-9195-5316c7ce2aff.PNG)
![SVL_Capture_24](https://user-images.githubusercontent.com/86273840/125830066-9573f701-b818-453c-a219-cb3d918a12e0.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-15 17:24
You need to replace the old maps/bridge with the new compatible ones in the simulation

**Comment by DestinyFrank** [comment] 2021-07-15 17:30
Which bridges and maps are compatible with the simulation? When I am looking at the other maps it's saying that none of them are. Also, we wanted to find a map that was a city area is there another one like the San Francisco one?

**Comment by EricBoiseLGSVL** [comment] 2021-07-15 17:46
what webui url are you using?  Hit ctrl F5 or delete cookies for the url because you should see updated assets

**Comment by DestinyFrank** [comment] 2021-07-15 17:52
I am unsure about WebUI I did not have the option in the simulator tab in unity which is where the tutorial said it would be. 
![SVL_Capture_26](https://user-images.githubusercontent.com/86273840/125834239-920a1612-d328-40fc-8ede-09913a67a1ba.PNG)
 said it would be.

**Comment by thisisdavidfrank** [comment] 2021-07-15 18:02
@DestinyFrank, WebUI is just a term we use for the the user interface on your browser. Please go to the browser where you are seeing this incompatibility errors, and try a hard-refresh (can be done by using Ctrl + F5). This should clear your local browser cache's stale data and reload it with the compatible versions.

**Comment by EricBoiseLGSVL** [comment] 2021-07-15 18:02
Why are you on Unity Editor 2020.3.12f1?  This is not right.  You need to be on 2020.3.3f1 per our documentation.  I'm guessing you are on wise.svlsimulator then but you can check in the bottom left in loader scene after hitting play mode. You may need to reclone everything because you are using a version of unity that is not supported

**Comment by heeen** [comment] 2021-07-15 18:03
It looks like on wise.svlsimulator.com San Francisco is not marked as compatible with Development & dev.

**Comment by EricBoiseLGSVL** [comment] 2021-07-15 18:07
Darn looks like this needs fixed in the back-end.  @eagafonovlge

**Comment by eagafonovlge** [comment] 2021-07-15 20:04
@DestinyFrank 
What is the exact version of the simulator your build is based on?

Looks like it is not 2021.2 and it's not 2021.1 either, but something in between. Could you please pick 2021.2 version as the base version for your changes?

**Comment by DestinyFrank** [comment] 2021-07-16 18:38
I have tried to download different versions of Unity and the simulator files but I am still really confused. @EricBoiseLGSVL would it be possible to set up a meeting or is there a person I can contact? I have been working on this project for a couple of weeks and I am not sure how to move forward.

**Comment by EricBoiseLGSVL** [comment] 2021-07-16 19:28
- Download Unity Editor 2020.3.3f1, remove versions not supported
- Delete all local AppData folders for simulator
- Clone release 2021.2 simulator into a new folder
- Clone release 2021.2 tags for any open source repos you are using to this new project
- Use wise.svlsimulator.com cloud url
- Remove all assets/clusters/simulations in your library in webui.
- Create a simple simulation with the Jaguar/Borregas/KeyboardSensor
- Run the simulator from LoaderScene in Editor.

Once this runs without errors, we can try to find out why you cannot add a new vehicle.  Because you are using the wrong Unity version, there is no point in screen sharing.  Let's get a clean slate first.

**Comment by DestinyFrank** [comment] 2021-07-19 17:35
@EricBoiseLGSVL I followed those steps and was able to load the simulator into Unity. After doing that, I tried to create a simulation, but it would not like me to select a map, but I could choose a vehicle. It's not giving me any error messages telling me why it's not connecting.  
![SVL_Capture_28](https://user-images.githubusercontent.com/86273840/126202484-c50e80e4-bd29-4c6f-9b4e-91eebc469957.PNG)
![SVL_Capture_29](https://user-images.githubusercontent.com/86273840/126202486-b50bf3b2-de4f-4d91-953d-29cb06c6b6e6.PNG)
![SVL_Capture_30](https://user-images.githubusercontent.com/86273840/126202487-1a13e2e3-f485-43d2-bd46-e6d48c7f4954.PNG)
![SVL_Capture_31](https://user-images.githubusercontent.com/86273840/126202488-3a3b59e7-449e-430d-8636-e2ea9d715619.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-19 19:30
@DestinyFrank It seems you don't have the assets that supports development.  Any idea @eagafonovlge or @thisisdavidfrank ?

**Comment by lemketron** [comment] 2021-07-19 19:30
> After doing that, I tried to create a simulation, but it would not like me to select a map, but I could choose a vehicle. It's not giving me any error messages telling me why it's not connecting.

You'll need to select a map. Are you saying there were no choices available?  If so then you'll need to add a map to your library. To add the Borregas map, go here:
https://wise.svlsimulator.com/maps/profile/aae03d2a-b7ca-4a88-9e41-9035287a12cc

And click "Add to Library" in the upper right corner. Then you should be able to return to your simulation and select the Map.

**Comment by EricBoiseLGSVL** [comment] 2021-07-19 19:33
It looks like those are added but not compatible with the development version. Those may be the old ones though.  @DestinyFrank please try to remove all maps in your library in webui maps and then ctrl f5 and then add borregas from the public ones.

**Comment by DestinyFrank** [comment] 2021-07-20 14:11
@EricBoiseLGSVL The map says that is it not compatible with the simulation cluster version. Also, I was wondering if you had a chance to try on your end to upload the vehicle with the files I sent? 
![SVL_Capture_32](https://user-images.githubusercontent.com/86273840/126337447-1da53917-e854-453d-b2fc-8c15b421cfe4.PNG)
![SVL_Capture_33](https://user-images.githubusercontent.com/86273840/126337450-9c184c97-f5ed-4568-a30a-0ddd79f6993c.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-20 16:04
It seems the the map is not the latest.  I'll ping @eagafonovlge and @thisisdavidfrank on this.  You are on wise.svlsimulator.com and release 2021.2 right?

**Comment by DestinyFrank** [comment] 2021-07-20 16:06
Okay thank you and yes I am on both of those. @EricBoiseLGSVL

**Comment by eagafonovlge** [comment] 2021-07-20 21:30
@DestinyFrank 
Please, unlink the simulator and link it again. It would refresh asset bundle format mapping for your Development simulator version, so 2021.2 release asst bundles would be marked as compatible.

**Comment by DestinyFrank** [comment] 2021-07-20 21:43
Thank you! It is now able to run the simulation in the unity editor. @eagafonovlge @EricBoiseLGSVL 

![SVL_Capture_35](https://user-images.githubusercontent.com/86273840/126399300-f71b26a7-36c9-4a1c-a061-8f8488c49951.PNG)

**Comment by eagafonovlge** [comment] 2021-07-20 21:46
You are welcome!

**Closed** 2021-07-20 21:47 UTC
Labels: answered

**Comment by DestinyFrank** [comment] 2021-07-22 15:19
@EricBoiseLGSVL @eagafonovlge Thank you for your help. I looked back at the tutorial to upload a new ego vehicle and it is now able to be seen in the simulation.  The only issue I having now is that when I press play the car and the screen seems to freeze. Is there a configuration I need to add or something I missed when creating the assets bundle? 
![SVL_Capture_39](https://user-images.githubusercontent.com/86273840/126664270-0e278fbe-53ea-49be-9964-ab4069b7ef34.PNG)
![SVL_Capture_41](https://user-images.githubusercontent.com/86273840/126664278-b6d38778-3914-4934-a4de-118eec73cd0a.PNG)
 ![SVL_Capture_40](https://user-images.githubusercontent.com/86273840/126650285-1fea7e63-a1d6-4fb2-b038-c006e0ea916c.PNG)

**Comment by EricBoiseLGSVL** [comment] 2021-07-22 17:45
When you press play in the UI at the bottom left the simulator freezes? Do you have errors in the console panel?

**Comment by DestinyFrank** [comment] 2021-07-22 17:55
Yes, once I click the play button it freezes. I can move the camera around and click the icons until I press the play button and I am not getting any error messages.

**Comment by EricBoiseLGSVL** [comment] 2021-07-22 19:18
Are you running the simulator in editor from the LoaderScene? How are you running the simulator?  It seems you have the play/pause state inverted.

**Comment by DestinyFrank** [comment] 2021-07-23 16:42
@EricBoiseLGSVL I am running the simulation in the LoaderScene. I am clicking run simulation on the website and then pressing play in the game view.

**Comment by EricBoiseLGSVL** [comment] 2021-07-23 17:19
Did you change any code for state?  The issue I see is that your simulation is paused but the button state is inverted. So when you press play the simulation actually pauses.  Do you have any errors in the console panel? If you have an error then the initialization will fail. Please screen shot the console panel or share your editor log? Another thing to check is what testcase template are you running from the webui?  What type of simulation are you running in the editor?

**Comment by DestinyFrank** [comment] 2021-07-23 17:25
@EricBoiseLGSVL I think that the issue is with the pause button. Once I pressed play I went and pressed the pause button for the game editor and it worked. I can use the arrow keys the move it now and all the wheels are moving in the right way.  Thank you so much for your help.

**Comment by EricBoiseLGSVL** [comment] 2021-07-23 17:31
Odd, you may have a editor setting that pauses on errors.  See [here](http://docs.unity3d.com/Manual/Console.html). Glad to help and that you resolved the issue.

**Comment by DestinyFrank** [comment] 2021-07-23 17:52
@EricBoiseLGSVL Thank you! I turned off the error pause and it works when I press the play button.
