### ISSUE TITLE
simulator stuck on 0% progress after pressing 'run simulation' button

### ISSUE THREAD

**Issue by beanmoon** [lgsvl/simulator#1816] opened 2021-10-15 07:27 UTC
![Screenshot from 2021-10-15 15-20-00](https://user-images.githubusercontent.com/2898794/137448545-a85c05a6-36ad-4dfa-94bf-861691ac7d40.png)
as seen above, after I create a simulation and press 'run simulation' button, the simulator reacted accordingly but got stuck on the downloading state with 0% progress,  any ideas?

**Comment by ihsanyalcinkaya** [comment] 2021-10-15 08:05
I am having the same problem. I think, root cause is same with #1815. It seems that servers are down.

**Comment by EricBoiseLGSVL** [comment] 2021-10-15 14:56
Yep, closing this because #1815 is tracking this and it's a dupe but thanks for posting.  We are on this and sorry for the downtime.  We will fix asap

**Closed as completed** 2021-10-15 14:56 UTC
Labels: duplicate
