### ISSUE TITLE
is there a semi-truck available

### ISSUE THREAD

**Issue by manone888** [lgsvl/simulator#1093] opened 2020-10-27 02:21 UTC
Hi, thank you for the great simulator.

I would like to know that is there a semi-truck available? Because I'd like to simulate autonomous driving for a semi-truck. If it is not available, is there a way to create or import it? Please kindly advise me.

Thank you so much for your help!

**Comment by EricBoiseLGSVL** [comment] 2020-10-27 18:25
@manonechu  Thanks!  We are working on supporting semi-trucks but it is not ready yet.  You can create a NPC and then attach Unity FixedJoint components to the trailer.  You will also need to create a new LaneFollowBehaviour so you can adjust turn radius and behavior for this new NPC.  We hope to release examples soon.

**Comment by manonechu** [comment] 2020-10-27 18:34
Thank you for your response.
I really look forward to seeing the support for semi-trucks in the further
release and the examples you mentioned in the email. I will keep following.

**Comment by EricBoiseLGSVL** [comment] 2020-10-27 23:28
@manonechu No problem.  Be sure to reach out with any issues if you attempt to add a semi-truck on your own.

**Comment by manonechu** [comment] 2020-10-29 01:31
Thank you, Eric. Would it be easier to add a conventional truck than a
semi-truck? I attached a screenshot of the conventional truck below.
Thanks a lot.
[image: image.png]

**Comment by EricBoiseLGSVL** [comment] 2020-10-29 20:16
I don't see the image but yes a conventional truck would be much easier.  You can create a new npc and add it to the simulator internals.  We will also support external NPCs very soon.  The issue with a rig is that the fixed joint can be difficult to work with in Unity,

**Comment by manonechu** [comment] 2020-10-30 01:29
@EricBoiseLGSVL , thank you again for your help, Eric. I attached the figure again. I meant the conventional truck marked by the red rectangle. Because I took this figure from your [tutorial](https://www.lgsvlsimulator.com/docs/npc-map-navigation/), does it mean that you already have the support for it and I can add it from somewhere? Or I need to follow the tutorial [here](https://www.lgsvlsimulator.com/docs/add-new-ego-vehicle/) to create it by myself? 
Thanks a lot.
![NPCSetup](https://user-images.githubusercontent.com/19791379/97649204-b8698500-1a24-11eb-8b4b-db12634b707a.jpg)

**Comment by EricBoiseLGSVL** [comment] 2020-10-30 15:18
Cool, no this tutorial is for EGO vehicles.  You will need to add an NPC.  You will need to look at the other npcs and copy their setup and add the the internal list of npcs.  There is a issue about it here #755

**Comment by manonechu** [comment] 2020-11-01 02:32
@EricBoiseLGSVL, I really appreciate your generous help. 
I am thinking to design an autonomous driving system for BoxTrucks, i.e., I want to control the steering, throttle, and brake of BoxTrucks, via C++ and ROS. Would you please advise me on how to simulate the autonomous system in the LG simulator? Some steps would be great!

The BoxTruck is one of NPC vehicles. I would like to know if I can also control the steering, throttle, and brake of NPC vehicles, just like controlling Ego vehicles.

**Comment by EricBoiseLGSVL** [comment] 2020-11-02 17:20
@manonechu Yes you can use the box truck as an EGO vehicle.  I would look at the tutorial on how to add a new ego vehicle, use the NPC box truck, modify the mesh and make a new EGO.  Then you can control with ROS.  I'm not sure why you need to use C++, do you need a new vehicle control sensor?  You can make it in C# as a sensor plugin.

**Comment by manonechu** [comment] 2020-11-03 01:19
@EricBoiseLGSVL 
Thank you very much, Eric. That would be very helpful for me.
I can also go with Python plus ROS. But C++ seems to be a better language for development as Autoware and others are using it.
Please kindly let me know if you have an update of the tutorial on how to add a box truck as a new ego vehicle. I will pay attention to your online document, too.
Thank you again.

**Comment by EricBoiseLGSVL** [comment] 2020-11-03 02:54
@manonechu no sorry, this is the docs that will be updated on the next release.  This is the new tutorial [here](https://youtu.be/R_Z65kimCII)

**Comment by manonechu** [comment] 2020-11-04 02:21
@EricBoiseLGSVL , thank you very much, Eric. Hope you have your favorite president tonight.

**Comment by manonechu** [comment] 2020-11-10 05:46
@EricBoiseLGSVL, Hi Eric, when I set up the simulator and want to control the vehicle, why the type of topic "/vehicle_cmd" is "autoware_msgs/VehicleCmd"? How could I use the lgsvl/msgs to control the vehicle? I attached two screenshots of the simulator below.
Thank you so much for your help.
![20201109234113](https://user-images.githubusercontent.com/19791379/98632754-bab1c600-22e5-11eb-8112-7f66f67d53c9.png)
![20201109234205](https://user-images.githubusercontent.com/19791379/98632765-bd142000-22e5-11eb-97d8-4beb62f9a930.png)

**Comment by EricBoiseLGSVL** [comment] 2020-11-10 17:11
@hadiTab do you know why the topics are different?

**Comment by hadiTab** [comment] 2020-11-10 19:21
@manonechu this looks like a bug. I'm going to have to review it in more detail later, but it seems like right now whenever the bridge type is set to ROS it will expect the `autoware_msgs` control command.

**Comment by manonechu** [comment] 2020-11-10 21:53
Thank you, Hadi, will it work if I have a ROS node in which publishes
commands via the autoware_msgs?

Or do I need to use ROS2 instead to use the lgsvl/msgs?

Thanks a lot for your help.

**Comment by manonechu** [comment] 2020-11-12 22:11
@hadiTab Thank you, Hadi, will it work if I have a ROS node in which publishes
commands via the autoware_msgs?

Or do I need to use ROS2 instead to use the lgsvl/msgs?

Thanks a lot for your help.

**Comment by hadiTab** [comment] 2020-11-13 04:08
@manonechu both of those options would work.

**Comment by manonechu** [comment] 2020-11-13 04:22
@hadiTab thank you for your reply. In ROS, I publish commands via the autoware_msgs, but it seems that the vehicle only responses to the twist_cmd. Does it mean that I cannot directly control the steering angle?
When I select ROS2 in the vehicle setting in WebUI, as shown in the following picture, I can see the lgsvl/msgs and I can rostopic pub /vehicle ..., but the vehicle does not response.
![image](https://user-images.githubusercontent.com/19791379/99028250-ebd40580-2534-11eb-9574-7df7ed78422a.png)
I install ROS2 but I don't see the /vehicle topic when I ros2 topic list.
Could you please advise me?  Thanks a lot.

**Comment by hadiTab** [comment] 2020-11-13 07:26
@manonechu you are right. You need to use the /twist_cmd to control the vehicle using `autoware_msgs`. I believe the steering angle is mapped to the z-axis of the angular velocity part of the `twist_cmd` message. However, there is a bug in the Autoware control that makes it a bit hard to control the velocity precisely and because of that I would recommend using ROS2.
In ROS2 you can just use the [lgsvl_msgs](https://github.com/lgsvl/lgsvl_msgs) to control the car. It should just subscribe to the `VehicleControlData` message.

**Comment by manonechu** [comment] 2020-11-13 16:26
@hadiTab thank you very much for your reply.
When using ROS, I ran the [rosbridge](http://wiki.ros.org/rosbridge_suite) and published commands via autoware_msgs (twist_cmd).
My question is, when using ROS2, what rosbridge should I install/use? Right now, I have rosbridge from ROS1 running and use ROS2 to publish lgsvl_msgs, but the vehicle doesn't respond. And I type "ros2 topic list", it doesn't show any topics from the simulator.
Thank you for your help again.

**Comment by manonechu** [comment] 2020-11-14 04:23
@hadiTab thank you very much for your help.
I follow this [tutorial](https://www.lgsvlsimulator.com/docs/build-instructions/) to build LG simulator and this [tutorial](https://www.lgsvlsimulator.com/docs/ros2-bridge/) to set up the ROS 2 bridge.
I have an error to connect to the simulator. Could you please advise me on how to solve this issue? Thank you very much.
This is the vehicle:
![image](https://user-images.githubusercontent.com/19791379/99139457-6cab0400-25fe-11eb-84ee-759f1e73554d.png)
This is the simulation:
![image](https://user-images.githubusercontent.com/19791379/99139480-a5e37400-25fe-11eb-9b7f-50090f65a936.png)
This is the error I have:
![image](https://user-images.githubusercontent.com/19791379/99139473-95cb9480-25fe-11eb-9875-5587de587efe.png)

**Comment by hadiTab** [comment] 2020-11-14 07:30
@manonechu It looks like you are using an older version of the simulator that does not support the ros2-lgsvl-bridge. Did you build your own binary? If so, what branch did you use? The ros2-lgsvl-bridge only works with the 2020.06 release. You can download a prebuild binary for it from here: https://github.com/lgsvl/simulator/releases/tag/2020.06
If you need to build your own binary, make sure to checkout the `release-2020.06` branch before building.

**Comment by manonechu** [comment] 2020-11-14 21:08
@hadiTab Thank you very much for your help. I rebuilt the release-2020.06 and now the ros2-lgsvl-bridge can talk to the simulator.
I tried to publish the topic /vehicle_cmd to control the steering angle, throttle, and brake. However, the vehicle only responded to the /acceleration_pct and /acceleration_pct, but **not** to target_wheel_angle and target_wheel_angular_rate. Please see the below figure. 
Could you please advise on this issue? Thanks a lot.
![image](https://user-images.githubusercontent.com/19791379/99156928-d96be000-268a-11eb-99dd-be935c3bb3f1.png)

**Comment by hadiTab** [comment] 2020-11-14 21:19
Have you tried bigger numbers? I think the angle is in degrees (but not sure).

**Comment by manonechu** [comment] 2020-11-14 21:43
@hadiTab Thank you very much for your quick reply.
I increased the /target_wheel_angle to bigger values and the vehicle turned the front wheels! Thank you.
I also noticed that the vehicle will only turn the front wheels when the /target_wheel_angle is large than 0.68. And the front wheels will turn to **the same** position as long as the /target_wheel_angle is large than 0.68.
Please let me know if I am mistaken. 
Here is the [lgsvl_msgs](https://github.com/lgsvl/lgsvl_msgs/blob/master/msg/VehicleControlData.msg).

**Comment by hadiTab** [comment] 2020-11-15 07:15
@manonechu This is a bug that will be fixed in the next release. Sorry I forgot about it.
Look at [this comment](https://github.com/lgsvl/simulator/issues/1065#issuecomment-710689578) for a fix.

**Comment by manonechu** [comment] 2020-11-17 00:47
@hadiTab Thank you very much! I fixed the bug and the steering control works now.

**Closed** 2021-07-16 20:53 UTC
Labels: close soon, in progress

**Comment by Bmoradi93** [comment] 2021-11-02 21:39
@EricBoiseLGSVL 
Is the tractor-trailer system integrated into the vehicle library?
Please give us an update on this.
My MSc Thesis is designing a local planner for tractor-trailer systems in backward maneuvering.
I would like to use lgsvl in my research for the simulation part.
Thank you!

**Comment by EricBoiseLGSVL** [comment] 2021-11-03 00:38
@Bmoradi93 This feature is not yet finished but you can create a trailer system using the new articulated body components from unity.

**Comment by Bmoradi93** [comment] 2021-12-03 01:37
@EricBoiseLGSVL 
The problem is I do not know if it will be compatible with ROS2 (Getting topics and etc in ROS2 like the Lexus vehicle)
I'm done with my theoretical and python implementation. 
We would like to migrate from Gazebo to unity and looking for someone to help us in this direction.
His/her name will be included in our papers.
If you know someone, please introduce if possible.

**Comment by EricBoiseLGSVL** [comment] 2021-12-03 01:44
You could start an issue and I can mark it help wanted.  Describe what help you need and maybe others can contact or post
