### ISSUE TITLE
Unity Editor is freezing on play mode when pedestrian is added.

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#464] opened 2019-11-04 08:15 UTC
Hi everyone,
I tried to add pedestrian path for my map using map annotation tool. However, Unity Editor is freezing on play mode after adding the pedestrian path. Screenshots about this problem is added.
How can I overcome this problem. Thank you.

![2](https://user-images.githubusercontent.com/23841025/68106104-944a9500-fef1-11e9-80dd-97d399042c08.png)

![1](https://user-images.githubusercontent.com/23841025/68106080-7ed56b00-fef1-11e9-8227-38a5c3416e6b.png)

![3](https://user-images.githubusercontent.com/23841025/68106939-3bc8c700-fef4-11e9-8e6c-476c3f12e971.png)

**Comment by shalinmehtalgsvl** [comment] 2019-11-04 19:28
Hi @clepz ,

I was able to recreate your issue and the problem is that we did not include a NavMesh with Shalun (will be updated in next push). To generate your own here are the steps:

1. Open AI > Navigation menu
<img width="316" alt="navmesh_menu_location" src="https://user-images.githubusercontent.com/44508098/68150908-88f96880-fef5-11e9-9831-457be0962a79.png">

2. Select the Meshes that you want to include in the NavMesh. (In this screenshot I have only included the sidewalks). Check the `Navigation Static` box and then select the type of area the mesh is. You can select multiple meshes at the same time, but they will all be marked as the same type of area (so do all sidewalks, then do all roads, then do all grass, ...). 
<img width="1913" alt="set_navmesh_area" src="https://user-images.githubusercontent.com/44508098/68151067-e097d400-fef5-11e9-84d5-a7f3a16de3e5.png">

3. Bake NavMesh. After baking, the NavMesh will be displayed in the scene view. In the screenshot I only baked a NavMesh on the sidewalks (green polygons). If you have set other meshes, they will be colored based on the `Navigation Area` set for the mesh. 
<img width="1640" alt="created_navmesh" src="https://user-images.githubusercontent.com/44508098/68151194-150b9000-fef6-11e9-886a-c6254cce9662.png">

**Comment by clepz** [comment] 2019-11-05 04:52
Thank you. It works perfectly.

**Closed** 2019-12-29 14:11 UTC
