### ISSUE TITLE
Editing Map in unity editor

### ISSUE THREAD

**Issue by asifsid-32** [lgsvl/simulator#1025] opened 2020-09-29 04:32 UTC
Hello Team,

I am facing issues in loading up the screen in unity editor. I have followed all the points from the given link https://www.lgsvlsimulator.com/docs/add-new-map/#import-assets. When i run the scene in unity editor i get a blank screen in which my ego car falls from the sky. 

Please find attached screenshot of the same. 
![unity](https://user-images.githubusercontent.com/69885768/94512870-d59b1000-023a-11eb-98b6-f1f141257ead.png)

**Comment by asifsid-32** [comment] 2020-09-29 08:25
> Hello Team,
> 
> I am facing issues in loading up the screen in unity editor. I have followed all the points from the given link https://www.lgsvlsimulator.com/docs/add-new-map/#import-assets. When i run the scene in unity editor i get a blank screen in which my ego car falls from the sky.
> 
> Please find attached screenshot of the same.
> ![unity](https://user-images.githubusercontent.com/69885768/94512870-d59b1000-023a-11eb-98b6-f1f141257ead.png)

Followings issues i faced when i checked it - 
![unity2](https://user-images.githubusercontent.com/69885768/94532331-59fd8b00-025b-11eb-9182-9f14864817b1.png)

**Comment by EricBoiseLGSVL** [comment] 2020-09-29 16:06
Don't worry about check, that is more of an internal check for assets.  Be sure to use git lfs pull to make sure you have assets.  You can check that textures are not URLs but actual .png files.

**Comment by asifsid-32** [comment] 2020-09-29 16:09
> Don't worry about check, that is more of an internal check for assets.  Be sure to use git lfs pull to make sure you have assets.  You can check that textures are not URLs but actual .png files.

@EricBoiseLGSVL about the ego vehicle falling from the sky that is the issue ? Also what has to be done to load the actual map in the scene to edit it.

**Comment by EricBoiseLGSVL** [comment] 2020-09-29 16:16
If you do not have git lfs installed when cloning the repo, you will not have mesh assets.  If you don't have textures (you won't see anything) and if you don't have meshes (you won't have collider data) and the vehicle will fall.  It's odd you have the vehicle assets and not the map.  Did you edit the map at all?

**Comment by asifsid-32** [comment] 2020-09-29 16:20
> If you do not have git lfs installed when cloning the repo, you will not have mesh assets.  If you don't have textures (you won't see anything) and if you don't have meshes (you won't have collider data) and the vehicle will fall.  It's odd you have the vehicle assets and not the map.  Did you edit the map at all?

I installed git lfs. No I am trying to load the scene first. Then I have to add calib patterns to it. I downloaded the single lane road map and added it to the path external/environments/singleroadmap 

Not able to find out the issue here !! Can you please help ?

**Comment by EricBoiseLGSVL** [comment] 2020-09-29 17:01
@asifsid-32 Can you please screen shot what the map looks like without running it so I can see the spawnInfo position and the collider on the road.

**Comment by asifsid-32** [comment] 2020-09-29 17:07
> @asifsid-32 Can you please screen shot what the map looks like without running it so I can see the spawnInfo position and the collider on the road.

PFA screenshots for the same .... 
![Screenshot (33)](https://user-images.githubusercontent.com/69885768/94590496-5d693480-02a4-11eb-9f5e-e098c0f40478.png)
![Screenshot (32)](https://user-images.githubusercontent.com/69885768/94590503-62c67f00-02a4-11eb-8e4a-de67c104c496.png)
![Screenshot (31)](https://user-images.githubusercontent.com/69885768/94590517-6823c980-02a4-11eb-8fef-b4e8c4b48939.png)

**Comment by EricBoiseLGSVL** [comment] 2020-09-29 17:34
Can you please open the Scene tab like so
![MapHelp00](https://user-images.githubusercontent.com/45106230/94595219-882d9b80-0258-11eb-9e04-9682ee1fb573.png)

**Comment by asifsid-32** [comment] 2020-09-29 17:46
> Can you please open the Scene tab like so
> ![MapHelp00](https://user-images.githubusercontent.com/45106230/94595219-882d9b80-0258-11eb-9e04-9682ee1fb573.png)
> 
> Game tab is only for when Editor is playing. Since simulator spawns scene cameras on play, there is no image in this tab when not playing. You also need to start simulation from loader scene, not the map scene. You build the map bundle and add path to map path in WebUI. Developer settings are still WIP and may have issues.
@EricBoiseLGSVL there's no tab as Scene, just the game tab i am able to find. Also i was able to start the loaderscene but when i run it stops at the "API Ready" page.

PFA ss from the unity 
![Screenshot (35)](https://user-images.githubusercontent.com/69885768/94596442-bedfd200-02a9-11eb-8702-26836c2a9e3d.png)
![Screenshot (37)](https://user-images.githubusercontent.com/69885768/94596449-c1dac280-02a9-11eb-9cc8-419706c11ebd.png)

**Comment by asifsid-32** [comment] 2020-09-29 17:49
> Can you please open the Scene tab like so
> ![MapHelp00](https://user-images.githubusercontent.com/45106230/94595219-882d9b80-0258-11eb-9e04-9682ee1fb573.png)
> 
> Game tab is only for when Editor is playing. Since simulator spawns scene cameras on play, there is no image in this tab when not playing. You also need to start simulation from loader scene, not the map scene. You build the map bundle and add path to map path in WebUI. Developer settings are still WIP and may have issues.

Just Got the scene tab .. 
![Screenshot (39)](https://user-images.githubusercontent.com/69885768/94596722-26961d00-02aa-11eb-83af-d2d3e4ff577b.png)

**Comment by asifsid-32** [comment] 2020-09-29 18:08
Following error i am getting when i opened the .png file present in the materials folder ....
So does this means that lfs wasn't installed properly ? Do i have to install it again ?
![Screenshot (43)](https://user-images.githubusercontent.com/69885768/94598525-ae7d2680-02ac-11eb-8c58-f91d0bd4b578.png)

**Comment by martins-mozeiko** [comment] 2020-09-29 19:23
Run `git lfs ls-files` in folder where you cloned the repository. It will print out status of all files under LFS. Each file **MUST** have an asterix (`*`) next to it. If you see only dash (`-`) that means git lfs files are not downloaded. In such case run `git lfs pull` and that will fix your repository.

For more information on git lfs see documentation here: https://www.atlassian.com/git/tutorials/git-lfs

**Comment by asifsid-32** [comment] 2020-09-30 03:38
> > If you do not have git lfs installed when cloning the repo, you will not have mesh assets.  If you don't have textures (you won't see anything) and if you don't have meshes (you won't have collider data) and the vehicle will fall.  It's odd you have the vehicle assets and not the map.  Did you edit the map at all?
> 
> I installed git lfs. No I am trying to load the scene first. Then I have to add calib patterns to it. I downloaded the single lane road map and added it to the path external/environments/singleroadmap 
> 
> Not able to find out the issue here !! Can you please help ?

@martins-mozeiko do I have to run from the loader scene or I can directly edit the map ??

**Comment by asifsid-32** [comment] 2020-09-30 04:48
> Run `git lfs ls-files` in folder where you cloned the repository. It will print out status of all files under LFS. Each file **MUST** have an asterix (`*`) next to it. If you see only dash (`-`) that means git lfs files are not downloaded. In such case run `git lfs pull` and that will fix your repository.
> 
> For more information on git lfs see documentation here: https://www.atlassian.com/git/tutorials/git-lfs

@EricBoiseLGSVL @martins-mozeiko Thanks for the support i am able to load the map in the unity editor. Now i want to place calibration patterns here. But in general i was using https://content.lgsvlsimulator.com/vehicles/lexusrx2016/ . So is it also open source or do i have to use Jaguar2015XE only. Also @EricBoiseLGSVL a little support on how to place calib patterns and reflect them back on simulator will prove a great help. 
![SS](https://user-images.githubusercontent.com/69885768/94644196-41967a80-0306-11eb-94d6-725a3ca45db1.png)

**Comment by asifsid-32** [comment] 2020-09-30 12:38
Hii @EricBoiseLGSVL , @martins-mozeiko 

I am not able to generate asset bundle file after making changes and building the simulator. Also when i run the loader screen it directly gets to API ready instead of open browser. 

PFA screenshot for the same 
![issue2](https://user-images.githubusercontent.com/69885768/94686005-d2417a80-0347-11eb-8eb7-05cccbaacb79.png)

**Comment by EricBoiseLGSVL** [comment] 2020-09-30 17:48
Did you build the new CubeTown asset?  Did you include windows support in the installation of Unity 2019.3.15f1?  You can do this in Unity Hub.  What errors do you get when you try to make a build?  Please look up how to get Editor logs in Unity.

Jaguar2015XE is our only open source vehicle but you can create private assets for vehicles.  It is up to you.  If you want to make a new vehicle, please see our tutorial on this [here](https://youtu.be/R_Z65kimCII).

I'm not sure on camera calibration but you could add the vehicle model into a scene, add a camera with the settings needed in the editor as a child of the vehicle as well as the calibration images on planes.  Then align the camera view to the real vehicle and save the transform data of the camera.  Then apply the position/rot of the camera to the sensor parameters in the simulation setup in the WebUI.

**Comment by asifsid-32** [comment] 2020-09-30 17:58
> Did you build the new CubeTown asset? Did you include windows support in the installation of Unity 2019.3.15f1? You can do this in Unity Hub. What errors do you get when you try to make a build? Please look up how to get Editor logs in Unity.
> 
> Jaguar2015XE is our only open source vehicle but you can create private assets for vehicles. It is up to you. If you want to make a new vehicle, please see our tutorial on this [here](https://youtu.be/R_Z65kimCII).
> 
> I'm not sure on camera calibration but you could add the vehicle model into a scene, add a camera with the settings needed in the editor as a child of the vehicle as well as the calibration images on planes. Then align the camera view to the real vehicle and save the transform data of the camera. Then apply the position/rot of the camera to the sensor parameters in the simulation setup in the WebUI.

@EricBoiseLGSVL is there a difference between building the simulator and building the CubeTown asset ? how do we have to build the CubeTown asset ?

Yes windows support is included in the istallation of unity 2019.3.15f1. When i build there were no errors and it got build successfully . 

But i am not able to find the environment_CubeTown file in assetbundle folder....

Any help will be appreciable ... Thanks in advance !!

**Comment by EricBoiseLGSVL** [comment] 2020-09-30 18:07
Is this a duplicate of #1034?  Please close the issue that is not needed

**Closed** 2020-09-30 18:13 UTC
Labels: answered
